poky.conf: Disable kernel version sanity check
Issue: LIN1021-702

By default, LINUX_VERSION is checked against version defined in kernel source
code. Sometimes syncing up kernel source with Yocto and rebasing oe-core may
not be done at the same time, these two versions might be different and cause
the following error.

ERROR: Package Version (5.10.46+gitAUTOINC+2327ef4bf4_3e27efe3e8) does not
match of kernel being built (5.10.37). Please update the PV variable to match
the kernel source or set KERNEL_VERSION_SANITY_SKIP="1" in your recipe.

This case would rarely happen and go away automatically later when the sync-up
is done. wrlinux distro has already ignored this, so should poky.

(LOCAL REV: NOT UPSTREAM) -- Wind River Specific

Signed-off-by: He Zhe <zhe.he@windriver.com>