README.hardware: update flashing instructions for MPC8315
Using 1000000 memory address for kernel and a00000 for dtb
can cause kernel image to overwrite dtb when uncompressing
and u-boot crashing with:
    ERROR: image is not a fdt - must RESET the board to recover.

Updated flashing instructions for the board to use addresses
1000000 and 2000000 to avoid this error.

Got rid of resetting loadaddr and ftdaddr u-boot variables.

Signed-off-by: Ed Bartosh <ed.bartosh@linux.intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>