poky.conf: Add MACHINE to SDK_NAME
Avoid errors from:
MACHINE=qemux86-64 bitbake core-image-sato:do_populate_sdk
then:
MACHINE=genericx86-64 bitbake core-image-sato:do_populate_sdk

which gives:

ERROR: core-image-sato-1.0-r0 do_populate_sdk: The recipe core-image-sato is trying
to install files into a shared area when those files already exist. Those files and
 their manifest location are:
  deploy/sdk/poky-glibc-x86_64-core-image-sato-core2-64-toolchain-2.6+snapshot.host.manifest
    (matched in manifest-qemux86_64x86_64-core-image-sato.populate_sdk)
  deploy/sdk/poky-glibc-x86_64-core-image-sato-core2-64-toolchain-2.6+snapshot.testdata.json
    (matched in manifest-qemux86_64x86_64-core-image-sato.populate_sdk)
  deploy/sdk/poky-glibc-x86_64-core-image-sato-core2-64-toolchain-2.6+snapshot.target.manifest
    (matched in manifest-qemux86_64x86_64-core-image-sato.populate_sdk)
  deploy/sdk/poky-glibc-x86_64-core-image-sato-core2-64-toolchain-2.6+snapshot.sh
    (matched in manifest-qemux86_64x86_64-core-image-sato.populate_sdk)
Please verify which recipe should provide the above files.

Adding MACHINE to the artefact name will avoid this. The issue was highlighted by
changes to the autobuilder configuration.

Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>